-- Database for daily tasks
-- German version by JoeLOTRO
-- coding: utf-8 'ä

Max_lvl = 105
DT_Data = {
	loc = {
	-- Eriador starts here
		["Gondamon"] = { loc="20.5s,97.0w", zone="Ered Luin", r=1, rep="TH" },--6-
		["Hobbingen"] = { loc="31.3s,71.2w", zone="Auenland", r=1, rep="MS" },--6-
		["Bree"] = { loc="30.2s,51.1w", zone="Breeland", r=1, rep="MB" },--14-20
		["Verlassene Herberge"] = { loc="34.0s,40.7w", zone="Einsame Lande", r=1, rep="TE" },--15-
		["Feste Guruth"] = { loc="31.4s,29.6w", zone="Einsame Lande", r=1, rep="TE" },--15-
		["Agamaur"] = { loc="29.6s,27.3w", zone="Einsame Lande", r=1, rep="TE" },--15-
		["Schragen"] = { loc="18.1s,53.8w", zone="Nordhöhen", r=1, rep="MB" },--20
		["Amon Raith"] = { loc="12.5s,52.8w", zone="Nordhöhen", r=1, rep="RE" },--20
		["Meluinen"] = { loc="13.7s,44.6w", zone="Nordhöhen", r=1, rep="RE" },--20
		["Othrikar"] = { loc="7.1s,45.0w", zone="Nordhöhen", r=1, rep="TH" },--20
		["Esteldin"] = { loc="9.7s,41.9w", zone="Nordhöhen", r=1, rep="RE" },--20
		["Hafergut"] = { loc="23.3s,67.4w", zone="Evendim", r=1, rep="MS" },--25
		["Tinnudir"] = { loc="12.6s,67.2w", zone="Evendim", r=1, rep="WA" },--25
		["Feste Forod"] = { loc="8.1s,64.2w", zone="Evendim", r=1, rep="--" },--25
		["Annuminas"] = { loc="19.1s,71.0w", zone="Evendim", r=1, rep="WA" },--33
		["Barachens Lager"] = { loc="34.0s,20.2w", zone="Trollhöhen", r=1, rep="TH" },--25
		["Thorenhad"] = { loc="31.6s,15.0w", zone="Trollhöhen", r=1, rep="ER" },--25.
		["Echad Candelleth"] = { loc="37.0s,14.2w", zone="Trollhöhen", r=1, rep="ER" },--25
		["Gloins Lager"] = { loc="24.7s,4.1w", zone="Nebelgebirge", r=1, rep="TH" },
		["Hohe Klippe"] = { loc="24.6s,1.3e", zone="Nebelgebirge", r=1, rep="TH" },
		["Hrimbarg"] = { loc="24.5s,7.0e", zone="Nebelgebirge", r=1, rep="TH" },
		["Kauppa-kohta"] = { loc="2.6n,58.0w", zone="Forochel", r=1, rep="LF" },
		["Pynti-peldot"] = { loc="11.4n,69.6w", zone="Forochel", r=1, rep="LF" },
		["Zigilgund"] = { loc="9.6n,80.8w", zone="Forochel", r=1, rep="--" },
		["Suri-kylä"] = { loc="19.0n,70.8w", zone="Forochel", r=1, rep="LF" },
		["Aughaire"] = { loc="0.0n,39.8w", zone="Angmar", r=1, rep="--" },
		["Tyrn Lhuig"] = { loc="1.7s,33.4w", zone="Angmar", r=1, rep="--" },
		["Gabilshathur"] = { loc="3.6s,26.5w", zone="Angmar", r=1, rep="--" },
		["Gath Forthnir"] = { loc="10.4n,24.1w", zone="Angmar", r=1, rep="CN" },
		["Gwingris"] = { loc="40.2s,16.0w", zone="Eregion", r=1, rep="--" },
		["Echad Mirobel"] = { loc="52.2s,17.0w", zone="Eregion", r=1, rep="--" },
		["Echad Dunann"] = { loc="50.6s,8.0w", zone="Eregion", r=1, rep="--" },
		["Lhan Tarren"] = { loc="75.3s,22.7w", zone="Dunland", r=1, rep="MD", nc=true },
		["Galtrev"] = { loc="80.1s,16.6w", zone="Dunland", r=1, rep="MD" },
		["Avardin"] = { loc="83.4s,20.6w", zone="Dunland", r=1, rep="MD", nc=true },
		["Barnavon"] = { loc="84.9s,16.5w", zone="Dunland", r=1, rep="MD", nc=true },
		["Kundschafterlager der Rohirrim"] = { loc="81.0s,10.6w", zone="Dunland", r=1, rep="TR", nc=true },
		["Voranbront"] = { loc="86.9s,7.4w", zone="Dunland", r=1, rep="TR" },
		["Grimbolds Lager"] = { loc="87.8s,3.9w", zone="Dunland", r=1, rep="TR", nc=true },
	-- Rhovanion starts here
		["Delfblick"] = { loc="8.5s,112.4w", zone="Moria", r=2, rep="IG" },--47
		["Tiefer Abgrund"] = { loc="9.8s,112.7w", zone="Moria", r=2, rep="IG" },
		["Der verrottende Keller"] = { loc="15.2s,111.7w", zone="Moria", r=2, rep="IG" },
		["Kammer des Scheidewegs"] = { loc="5.2s,111.9w", zone="Moria", r=2, rep="IG" },
		["Jazargund"] = { loc="4.0s,105.9w", zone="Moria", r=2, rep="IG" },
		["Einundzwanzigste Halle"] = { loc="6.3s,105.3w", zone="Moria", r=2, rep="IG" },
		["Die Ork-Wacht"] = { loc="11.2s,106.9w", zone="Moria", r=2, rep="IG" },
		["Anazarmekhem"] = { loc="13.5s,108.1w", zone="Moria", r=2, rep="IG" },
		["Überschattete Zuflucht"] = { loc="13.0s,101.6w", zone="Moria", r=2, rep="IG" },
		["Erste Halle"] = { loc="8.1s,95.3w", zone="Moria", r=2, rep="IG" },
		["Haldirith"] = { loc="21.4s,63.6w", zone="Großer Fluss", r=2, rep="RS" },
		["Stangard"] = { loc="25.4s,63.3w", zone="Großer Fluss", r=2, rep="RS" },
		["Der Cuthstan"] = { loc="25.8s,65.9w", zone="Großer Fluss", r=2, rep="RS" },
		["Limklar-Torhaus"] = { loc="25.5s,67.1w", zone="Großer Fluss", r=2, rep="RS" },
		["Parth Celebrant"] = { loc="26.6s,58.2w", zone="Großer Fluss", r=2, rep="RS" },
		["Aculfs Lager"] = { loc="39.1s,55.3w", zone="Großer Fluss", r=2, rep="RS" },
		["Etheburg"] = { loc="31.4s,52.1w", zone="Großer Fluss", r=2, rep="RS" },
		["Langhold"] = { loc="35.9s,53.6w", zone="Ost-Rohan", r=2, rep="--" },
		["Harwick"] = { loc="40.2s,52.0w", zone="Ost-Rohan", r=2, rep="--" },
		["Flutwend"] = { loc="45.7s,48.0w", zone="Ost-Rohan", r=2, rep="--" },
		["Stadt des Waldmeisters"] = { loc="43.3s,56.5w", zone="Ost-Rohan", r=2, rep="--" },
		["Elthengels"] = { loc="48.6s,52.6w", zone="Ost-Rohan", r=2, rep="--" },
		["Ohrenburg"] = { loc="47.6s,64.0w", zone="Ost-Rohan", r=2, rep="--" },
		["Feldheim"] = { loc="54.5s,57.4w", zone="Ost-Rohan", r=2, rep="--" },
		["Garsfeld"] = { loc="54.9s,61.7w", zone="Ost-Rohan", r=2, rep="--" },
		["Walstow"] = { loc="62.3s,54.2w", zone="Ost-Rohan", r=2, rep="--" },
		["Schneegrenze"] = { loc="60.5s,62.3w", zone="Ost-Rohan", r=2, rep="--" },
		["Forlach"] = { loc="39.3s,60.9w", zone="Wildermark", r=2, rep="PW" },
		["Aldburg"] = { loc="69.0s,64.5w", zone="West-Rohan", r=2, rep="Eo" },
		["Leuchtfeuerwacht"] = { loc="69.5s,56.9w", zone="West-Rohan", r=2, rep="Eo" },
		["Bachbrück"] = { loc="50.8s,77.7w", zone="West-Rohan", r=2, rep="Eo" },
		["Edoras"] = { loc="60.7s,74.2w", zone="West-Rohan", r=2, rep="Eo" },
		["Entfurt"] = { loc="56.2s,65.8w", zone="West-Rohan", r=2, rep="Eo" },
		["Fenmark"] = { loc="66.7s,57.2w", zone="West-Rohan", r=2, rep="Eo" },
		["Gapholt"] = { loc="53.7s,84.1w", zone="West-Rohan", r=2, rep="Eo" },
		["Grimslade"] = { loc="62.5s,82.1w", zone="West-Rohan", r=2, rep="Eo" },
		["Helms Klamm"] = { loc="63.8s,89.5w", zone="West-Rohan", r=2, rep="Eo" },
		["Mittelaue"] = { loc="53.5s,72.9w", zone="West-Rohan", r=2, rep="Eo" },
		["Ostweide"] = { loc="45.4s,67.1w", zone="West-Rohan", r=2, rep="Eo" },
		["Schlotheim"] = { loc="49.1s,69.5w", zone="West-Rohan", r=2, rep="Eo" },
		["Unterharg"] = { loc="67.4s,73.7w", zone="West-Rohan", r=2, rep="Eo" },
		["Holzmühle"] = { loc="47.4s,80.0w", zone="West-Rohan", r=2, rep="Eo" },
	-- Gondor starts here
		["Calembel"] = { loc="67.1s,55.9w", zone="West-Gondor", r=3, rep="DA" },
		["Dinadab"] = { loc="63.6s,59.1w", zone="West-Gondor", r=3, rep="DA" },
		["Dol Amroth"] = { loc="75.6s,72.2w", zone="West-Gondor", r=3, rep="DA" },
		["Morlad"] = { loc="56.9s,67.6w", zone="West-Gondor", r=3, rep="DA" },
		["Tadrent"] = { loc="74.1s,62.1w", zone="West-Gondor", r=3, rep="DA" },
		["Aerthir"] = { loc="83.9s,40.2w", zone="Zentrum Gondors", r=3, rep="Pe" },
		["Erynos"] = { loc="80.0s,32.8w", zone="Zentrum Gondors", r=3, rep="Pe" },
		["Ethring"] = { loc="71.8s,50.1w", zone="Zentrum Gondors", r=3, rep="Pe" },
		["Linhir"] = { loc="80.7s,45.5w", zone="Zentrum Gondors", r=3, rep="Pe" },
		["Malbarth"] = { loc="80.2s,42.3w", zone="Zentrum Gondors", r=3, rep="Pe" },
		["Feste Anglebed"] = { loc="79.2s,39.0w", zone="Zentrum Gondors", r=3, rep="Pe" },
		["Pelargir"] = { loc="83.0s,34.7w", zone="Zentrum Gondors", r=3, rep="Pe" },
		["Sarnhad"] = { loc="81.6s,43.9w", zone="Zentrum Gondors", r=3, rep="Pe" },
		["Glaniath"] = { loc="80.5s,29.8w", zone="Ost-Gondor", r=3, rep="RI" },
		["Tumladen"] = { loc="76.7s,29.6w", zone="Ost-Gondor", r=3, rep="RI" },
		["Arnach"] = { loc="76.6s,24.2w", zone="Ost-Gondor", r=3, rep="RI" },
		["Bar Hurin"] = { loc="73.3s,12.7w", zone="Ost-Gondor", r=3, rep="RI" },
		["Faramirs Aussichtspunkt"] = { loc="65.1s,6.2w", zone="Ost-Gondor", r=3, rep="RI" },
		["Minas Tirith"] = { loc="65.3s,16.7w", zone="Alt-Anorien", r=3, rep="DM" },
		["Crithost"] = { loc="54.1s,16.1w", zone="Alt-Anorien", r=3, rep="DM" },
		["Kleines Lager der Männer des Königs"] = { loc="45.3s,28.1w", zone="Weites Anorien", r=3, rep="RR" },
		["Feste Rimmon"] = { loc="46.8s,36.4w", zone="Weites Anorien", r=3, rep="RR" },
	},
	rz = {
		["Großer Fluss"] = "RS",
		["Ost-Rohan"] = "--",
		["West-Rohan"] = "Eo",
		["West-Gondor"] = "DA",
		["Zentrum Gondors"] = "Pe",
		["Ost-Gondor"] = "RI",
		["Alt-Anorien"] = "DM",
		["Weites Anorien"] = "RR",
	},
	lmap = {
		[75] = 68,	-- Großer Fluss
		[80] = 75,	-- Ost-Rohan
		[85] = 80,	-- Forlach
		[86] = 81,	-- West-Rohan
		[90] = 90,	-- West-Gondor
		[100] = 95, -- Zentrum/Ost-Gondor
		[105] = 100 -- Weites Anorien
	},
	rep = {
		["--"] = "<none>",
		CN = "Rat des Nordens",
		DA = "Dol Amroth",
		DM = "Verteidiger von Minas Tirith",
		Eo = "Die Eorlingas",
		ER = "Elben von Bruchtal",
		He = "Die Helmingas",
		HL = "Helden von Limklar",
		IG = "Minenbauer/Wächter der Eisernen Garnison",
		LF = "Lossoth von Forochel",
		MS = "Die Mathom-Gesellschaft",
		MB = "Menschen von Bree",
		MD = "Menschen aus Dunland",
		Pe = "Pelargir",
		PW = "Bewohner der Wildermark",
		RE = "Waldläufer von Esteldin",
		RI = "Waldläufer von Ithilien",
		RR = "Reiter von Rohan",
		RS = "Die Reiter von Stangard",
		TE = "Die Eglain",
		TH = "Thorins Halle",
		TR = "Theodreds Reiter",
		WA = "Die Hüter von Annuminas"
	},
	moriax = { ["Überschattete Zuflucht"]=true, ["Anazarmekhem"]=true, ["Die Ork-Wacht"]=true,
		["Erste Halle"]=true, ["Tiefer Abgrund"]=true, ["Jazargund"]=true,
		["Der verrottende Keller"]=true, ["Kammer des Scheidewegs"]=true
	},
	id = {
		["0DB1F"] = { N="Albino-Fell", H={ [46]="LF,--", [47]="--" },
				L = { ["Echad Mirobel"] = 41, ["Gwingris"] = 41,
					["Suri-kylä"] = 36, ["Echad Dunann"] = 41 } },
		["0DCC4"] = { N="Albino-Tierhaut", H={ [47]="LF,--", [48]="--" },
				L = { ["Echad Mirobel"] = 41, ["Echad Dunann"] = 41,
					["Suri-kylä"] = 36, ["Gath Forthnir"] = 49 } },
		["0DC45"] = { N="Verstärkter Panzer", H={ [47]="--", [48]="CN" },
				L = { ["Gath Forthnir"] = 48, ["Gwingris"] = 41 } },
		["0DEA2"] = { N="Klaue mit Widerhaken", H={ [53]="IG" },
				L = { ["Delfblick"] = 53, ["Tiefer Abgrund"] = 53, ["Jazargund"] = 53,
					["Der verrottende Keller"] = 53, ["Kammer des Scheidewegs"] = 53 } },
        ["0DFC5"] = { N="Wunderschöne Schwertscheide", H={ [57]="IG" },
				L = { ["Einundzwanzigste Halle"] = 57, ["Überschattete Zuflucht"] = 57,
					["Anazarmekhem"] = 57, ["Die Ork-Wacht"] = 57, ["Erste Halle"] = 57 } },
		["0DAE7"] = { N="Verbogene Klaue", H={ [10]="MS" },
				L = { ["Hobbingen"] = 6 } },
		["2770F"] = { N="Verbogener Metall-Streitkolben", H={ [65]="MD" },
				L = { ["Galtrev"] = 65,  ["Lhan Tarren"] = 65,
					["Avardin"] = 65, ["Barnavon"] = 65 } },
		["30476"] = { N="Verbogener Flügel", H={ [80.1]="--", [85]="PW" },
				L = { ["Ost-Rohan"] = 80, ["Forlach"] = 85 } },
		["0DD54"] = { N="Schwarzes Kernholz", H={ [30]="TE" },
				L = { ["Agamaur"] = 15 } },
		["3A74F"] = { N="Geschwärzter Schnabel", H={ [100]="Pe" },
				L = { ["Zentrum Gondors"] = 100 } },
		["0DC3E"] = { N="Geschwärzter Panzer", H={ [18]="MB" },
				L = { ["Bree"] = 18 } },
		["0DAE8"] = { N="Geschwärzter Dreck", H={ [14]="MB" },
				L = { ["Bree"] = 14 } },
		["0DB18"] = { N="Geschwärztes Fell", H={ [16]="MB", [20.1]="TE" },
				L = { ["Verlassene Herberge"] = 15, ["Bree"] = 16 } },
		["0DCBD"] = { N="Geschwärzte Tierhaut", H={ [17]="MB", [21]="TE" },
				L = { ["Bree"] = 17, ["Verlassene Herberge"] = 15 } },
		["0DCC8"] = { N="Geschwärzte Schwertscheide", H={ [17]="MB", [21]="TE" },
				L = { ["Verlassene Herberge"] = 15, ["Bree"] = 17 } },
		["2772A"] = { N="Gescheckte Tierhaut", H={ [71]="TR", [75]="RS", [80]="--" },
				L = { ["Kundschafterlager der Rohirrim"] = 71, ["Grimbolds Lager"] = 71,
					["Voranbront"] = 71, ["Großer Fluss"] = 75, ["Ost-Rohan"] = 80 } },
		["0DC5A"] = { N="Heller Staub", H={ [43]="LF" },
				L = { ["Kauppa-kohta"] = 36 } },
		["0F79E"] = { N="Zerbrochener Dolch", H={ [10]="TH", [11]="MS" },
				L = { ["Gondamon"] = 6, ["Hobbingen"] = 6 } },
		["0F795"] = { N="Zerbrochener Zweihänder", H={ [42]="LF,--", [43]="LF,TH", [44]="--" },
				L = { ["Zigilgund"] = 36, ["Hrimbarg"] = 38, ["Pynti-peldot"] = 36,
					["Kauppa-kohta"] = 36, ["Aughaire"] = 42, ["Gabilshathur"] = 41 } },
		["0F794"] = { N="Zerbrochene Hellebarde", H={ [38]="--,TH,WA", [41]="--" },
				L = { ["Aughaire"] = 38, ["Tyrn Lhuig"] = 41,
					["Gloins Lager"] = 38, ["Hohe Klippe"] = 38, ["Annuminas"] = 33 } },
		["0F78E"] = { N="Zerbrochenes Beil", H={ [14]="MB" },
				L = { ["Bree"] = 14 } },
		["0F797"] = { N="Zerbrochener Langbogen", H={ [49]="--" },
				L = { ["Echad Mirobel"] = 41 } },
		["0F793"] = { N="Zerbrochenes Langschwert", H={ [33]="WA", [34]="--", [35]="ER,--,TH" },
				L = { ["Feste Forod"] = 25, ["Tinnudir"] = 25, ["Thorenhad"] = {l=22,r='--'},
					["Barachens Lager"] = 22, ["Echad Candelleth"] = 22 } },
		["0F792"] = { N="Zerbrochener Kurzbogen", H={ [28]="RE", [29]="TE", [31]="WA" },
				L = { ["Hafergut"] = 25, ["Tinnudir"] = 25,
					["Esteldin"] = 21, ["Agamaur"] = 15 } },
		["0DCD1"] = { N="Zerbrochene Schwertscheide", H={ [11]="MS,TH", [28]="MS" },
				L = { ["Hobbingen"] = 6, ["Gondamon"] = 11 } },
		["0F791"] = { N="Zerbrochener Holzspeer", H={ [23]="MB,RE", [24]="RE,TE", [26]="TH" },
				L = { ["Schragen"] = 21, ["Esteldin"] = 21, ["Othrikar"] = 21,
					["Amon Raith"] = 21, ["Meluinen"] = 21, ["Feste Guruth"] = 15 } },
		["0F796"] = { N="Zerbrochene Holzkeule", H={ [46]="--", [47]="CN,LF,--" },
				L = { ["Echad Mirobel"] = 41, ["Echad Dunann"] = 41,
					["Gwingris"] = 41, ["Suri-kylä"] = 36, ["Gath Forthnir"] = 47 } },
		["0F78F"] = { N="Zerbrochener Holz-Streitkolben", H={ [16]="MB", [20.1]="TE" },
				L = { ["Verlassene Herberge"] = 15, ["Bree"] = 16 } },
		["0DBA9"] = { N="Wulstiger Schleim", H={ [20]="MB" },
				L = { ["Bree"] = 20 } },
		["0DB25"] = { N="Unebene Schuppe", H={ [29]="RE" },
				L = { ["Esteldin"] = 21 } },
		["3F1E4"] = { N="Verbranntes Ohr", H={ [105]="RR" },
				L = { ["Weites Anorien"] = 105 } },
		["0DFC3"] = { N="Bezaubernde Schwertscheide", H={ [53]="IG" },
				L = { ["Delfblick"] = 53, ["Tiefer Abgrund"] = 53, ["Jazargund"] = 53,
					["Der verrottende Keller"] = 53, ["Kammer des Scheidewegs"] = 53 } },
		["0DC01"] = { N="Sauberer Schwanz", H={ [45]="--" },
				L = { ["Zigilgund"] = 36, ["Gabilshathur"] = 45 } },
		["3A790"] = { N="Gekapptes Ohr", H={ [85]="He", [100]="DM,RI" },
				L = { ["West-Rohan"] = {l=81,r='He'}, ["Ost-Gondor"] = 100, ["Alt-Anorien"] = 100 } },
		["3A74E"] = { N="Gestutzter Flügel", H={ [85]="He", [100]="RI" },
				L = { ["West-Rohan"] = {l=81,r='He'}, ["Ost-Gondor"] = 100 } },
		["0DB1A"] = { N="Derbes Fell", H={ [22]="TE", [23]="RE", [26]="TE,TH" },
				L = { ["Amon Raith"] = 21, ["Verlassene Herberge"] = 15, ["Schragen"] = 20,
					["Othrikar"] = 21, ["Esteldin"] = 21, ["Feste Guruth"] = 15 } },
		["0DCBF"] = { N="Derbe Tierhaut", H={ [21]="MB", [23]="TE", [24]="RE", [25]="RE", [27]="TH" },
				L = { ["Meluinen"] = 21, ["Othrikar"] = 21, ["Esteldin"] = 21,
					["Verlassene Herberge"] = 15, ["Amon Raith"] = 21, ["Schragen"] = 18 } },
		["3048B"] = { N="Verdrehtes Ohr", H={ [80]="--" },
				L = { ["Ost-Rohan"] = 80 } },
		["0DC1F"] = { N="Geborstener Schnabel", H={ [21]="TE" },
				L = { ["Verlassene Herberge"] = 15 } },
		["0DEA8"] = { N="Unheimlicher Dreck", H={ [53]="IG" },
				L = { ["Delfblick"] = 53, ["Tiefer Abgrund"] = 53, ["Jazargund"] = 53,
					["Der verrottende Keller"] = 53, ["Kammer des Scheidewegs"] = 53 } },
		["0DFBE"] = { N="Unheimliche Tierhaut", H={ [57]="IG" },
				L = { ["Einundzwanzigste Halle"] = 57, ["Überschattete Zuflucht"] = 57,
					["Anazarmekhem"] = 57, ["Die Ork-Wacht"] = 57, ["Erste Halle"] = 57 } },
		["0DC2C"] = { N="Schiefer Ast", H={ [29]="TE" },
				L = { ["Agamaur"] = 15 } },
		["3A74B"] = { N="Beschädigte Klaue", H={ [100]="DM,Pe" },
				L = { ["Zentrum Gondors"] = 100, ["Alt-Anorien"] = 100 } },
		["3048C"] = { N="Beschädigtes Ohr", H={ [85]="PW" },
				L = { ["Forlach"] = 85 } },
		["3A752"] = { N="Beschädigtes Fell", H={ [85]="He", [100]="DA,Pe,RI" },
				L = { ["West-Rohan"] = {l=81,r='He'},
					["West-Gondor"] = 90, ["Zentrum Gondors"] = 100, ["Ost-Gondor"] = 100 } },
		["27724"] = { N="Dekorative Schwertscheide", H={ [71]="TR", [75]="RS", [80]="--" },
				L = { ["Kundschafterlager der Rohirrim"] = 71, ["Grimbolds Lager"] = 71,
					["Voranbront"] = 71, ["Großer Fluss"] = 75, ["Ost-Rohan"] = 80 } },
		["0DAF5"] = { N="Poröser Fingerknochen", H={ [29]="TE" },
				L = { ["Agamaur"] = 15 } },
		["0DC56"] = { N="Trüber Staub", H={ [25]="RE" },
				L = { ["Amon Raith"] = 21 } },
		["0DB88"] = { N="Schmutziges Ohr", H={ [12]="MS" },
				L = { ["Hobbingen"] = 6 } },
		["0DAF1"] = { N="Dreckhaufen", H={ [8]="MS", [12]="TH" },
				L = { ["Gondamon"] = 6, ["Hobbingen"] = 6 } },
		["0DB6A"] = { N="Schmutziger Flügel", H={ [8]="TH", [10]="MS" },
				L = { ["Gondamon"] = 8, ["Hobbingen"] = 6 } },
		["0DC28"] = { N="Matter Schnabel", H={[8]="TH" },
				L = { ["Gondamon"] = 6 } },
		["0DB80"] = { N="Dunkles Ohr", H={ [20]="MB" },
				L = { ["Bree"] = 20 } },
		["0DB61"] = { N="Dunkler Flügel", H={ [18]="MB", [20.1]="TE" },
				L = { ["Verlassene Herberge"] = 15, ["Bree"] = 18 } },
		["0DEC8"] = { N="Elegante Schuppe", H={ [57]="IG" },
				L = { ["Einundzwanzigste Halle"] = 57, ["Überschattete Zuflucht"] = 57,
					["Anazarmekhem"] = 57, ["Die Ork-Wacht"] = 57, ["Erste Halle"] = 57 } },
		["0DFC4"] = { N="Elegante Schwertscheide", H={ [57]="IG" },
				L = { ["Einundzwanzigste Halle"] = 57, ["Überschattete Zuflucht"] = 57,
					["Anazarmekhem"] = 57, ["Die Ork-Wacht"] = 57, ["Erste Halle"] = 57 } },
		["3F1E9"] = { N="Elbische Schwertscheide", H={ [105]="RR" },
				L = { ["Weites Anorien"] = 105 } },
		["0DC44"] = { N="Vergrösserter Panzer", H={ [41]="--" },
				L = { ["Tyrn Lhuig"] = 41 } },
		["0DC24"] = { N="Extrem scharfer Schnabel", H={ [40.1]="TH" },
				L = { ["Gloins Lager"] = 38, ["Hohe Klippe"] = 38 } },
		["0DAE2"] = { N="Extrem scharfe Klaue", H={ [35]="ER,TH" },
				L = { ["Thorenhad"] = 22, ["Barachens Lager"] = 22, ["Echad Candelleth"] = 22 } },
		["2772E"] = { N="Vergängliche Essenz", H={ [75]="RS" },
				L = { ["Großer Fluss"] = 75 } },
		["30490"] = { N="Stinkender Dreck", H={ [80]="--" },
				L = { ["Ost-Rohan"] = 80 } },
		["0DBCB"] = { N="Edle Feather", H={ [35]="ER" },
				L = { ["Thorenhad"] = 22 } },
		["0DB1C"] = { N="Edles Fell", H={ [34]="--", [35]="ER,TH" },
				L = { ["Feste Forod"] = 25, ["Thorenhad"] = 22,
					["Barachens Lager"] = 22 } },
		["0DCC1"] = { N="Edle Tierhaut", H={ [35]="ER,--,TH" },
				L = { ["Feste Forod"] = 25, ["Thorenhad"] = 22,
					["Echad Candelleth"] = 22, ["Barachens Lager"] = 22 } },
		["0DB81"] = { N="Fehlerhaftes Ohr", H={ [22]="MB", [24]="TE", [27]="RE" },
				L = { ["Esteldin"] = 21, ["Feste Guruth"] = 15, ["Schragen"] = 21 } },
		["0DBAA"] = { N="Fehlerhafter Schleim", H={ [25]="RE,TE", [26]="RE" },
				L = { ["Meluinen"] = 21, ["Esteldin"] = 21, ["Feste Guruth"] = 15 } },
		["3047C"] = { N="Flaumiger Flügel", H={ [80]="--" },
				L={ ["Ost-Rohan"] = 80 } },
		["0DCCE"] = { N="Vergoldete Schwertscheide", H={ [44]="LF,--,TH", [45]="--" },
				L = { ["Zigilgund"] = 36, ["Hrimbarg"] = 38, ["Pynti-peldot"] = 36,
					["Aughaire"] = 43, ["Kauppa-kohta"] = 36, ["Tyrn Lhuig"] = 41,
					["Gabilshathur"] = 44 } },
		["2772D"] = { N="Glasiger Panzer", H={ [75]="RS" },
				L = { ["Großer Fluss"] = 75 } },
		["3A754"] = { N="Schimmernder Staub", H={ [100]="DA" },
				L = { ["West-Gondor"] = 90 } },
		["0DB94"] = { N="Schillernde Essenz", H={ [20]="MB" },
				L = { ["Bree"] = 20 } },
		["0DAE9"] = { N="Schillernder Dreck", H={ [19]="MB" },
				L = { ["Bree"] = 19 } },
		["3A799"] = { N="Glitzernde Schwertscheide", H={ [85]="Eo" },
				L = { ["West-Rohan"] = 86 } },
		["0DB96"] = { N="Gleissende Essenz", H={ [25]="RE", [27]="TE" },
				L = { ["Amon Raith"] = 21, ["Feste Guruth"] = 15 } },
		["0DB85"] = { N="Prächtiges Ohr", H={ [45]="TH" },
				L = { ["Hrimbarg"] = 38 } },
		["0DAEE"] = { N="Prächtiger Dreck", H={ [42]="LF", [47]="--" },
				L = { ["Gabilshathur"] = 45, ["Kauppa-kohta"] = 36 } },
		["0DCAE"] = { N="Prächtige Membran", H={ [46]="--" },
				L = { ["Gabilshathur"] = 46 } },
		["0DB28"] = { N="Prächtige Schuppe", H={ [44]="--", [45]="LF" },
				L = { ["Zigilgund"] = 36, ["Suri-kylä"] = 36 } },
		["0DB83"] = { N="Graues Ohr", H={ [35]="ER,TH" },
				L = { ["Thorenhad"] = 22, ["Barachens Lager"] = 22 } },
		["0DBAC"] = { N="Grauer Schleim", H={ [35]="ER" },
				L = { ["Echad Candelleth"] = 22 } },
		["0DD55"] = { N="Graues Kernholz", H={ [35]="ER" },
				L = { ["Thorenhad"] = 22 } },
		["0DC42"] = { N="Gehärteter Panzer", H={ [35]="ER" },
				L = { ["Echad Candelleth"] = 22, ["Thorenhad"] = 22 } },
		["0DC41"] = { N="Schwerer Panzer", H={ [28]="TE", [29]="MS", [33]="WA" },
				L = { ["Hafergut"] = 25, ["Tinnudir"] = 25, ["Agamaur"] = 15 } },
		["0DCCB"] = { N="Schwere Schwertscheide", H={ [30]="MS,RE,TE", [32]="WA" },
				L = { ["Hafergut"] = 25, ["Esteldin"] = 21, ["Tinnudir"] = 25, ["Agamaur"] = 15 } },
		["0DB84"] = { N="Riesiges Ohr", H={ [41]="--,TH" },
				L = { ["Gloins Lager"] = 38, ["Hohe Klippe"] = 38, ["Aughaire"] = 41 } },
		["0DAED"] = { N="Riesiger Dreckhaufen", H={ [38]="--", [41]="--" },
				L = { ["Tyrn Lhuig"] = 41, ["Aughaire"] = 38 } },
		["0DBAD"] = { N="Riesiger Schleim", H={ [41]="--" },
				L = { ["Aughaire"] = 41 } },
		["0DD56"] = { N="Riesiges Kernholz", H={ [40.1]="TH" },
				L = { ["Gloins Lager"] = 38, ["Hohe Klippe"] = 38 } },
		["0DB27"] = { N="Riesige Schuppe", H={ [41]="TH" },
				L = { ["Gloins Lager"] = 38, ["Hohe Klippe"] = 38 } },
		["0DB66"] = { N="Riesiger Flügel", H={ [39]="TH" },
				L = { ["Gloins Lager"] = 38, ["Hohe Klippe"] = 38 } },
		["0DC21"] = { N="Zerfurchter Schnabel", H={ [21]="RE", [23]="TE", [26]="RE", [28]="TH" },
				L = { ["Othrikar"] = 21, ["Verlassene Herberge"] = 15,
					["Esteldin"] = 21, ["Schragen"] = {l=21,r='RE'} } },
		["0DADE"] = { N="Zerfurchte Klaue", H={ [18]="MB" },
				L = { ["Bree"] = 18 } },
		["0DBAB"] = { N="Gallertartiger Schleim", H={ [30]="MS" },
				L = { ["Hafergut"] = 25 } },
		["0DCCF"] = { N="Juwelenbesetzte Schwertscheide", H={ [47]="--", [48]="--" },
				L = { ["Echad Mirobel"] = 41, ["Echad Dunann"] = 41, ["Gath Forthnir"] = 49 } },
		["0DC2D"] = { N="Knotiger Ast", H={ [35]="ER" },
				L = { ["Thorenhad"] = 22 } },
		["2771F"] = { N="Knotiges Kernholz", C=1, H={ [75]="HL" },
				L = { ["Großer Fluss"] = {l=68,r='HL'} } },
		["0DAEA"] = { N="Grosser Dreckhaufen", H={ [22]="TE", [23]="RE", [24]="RE", [26]="TE" },
				L = { ["Meluinen"] = 21, ["Verlassene Herberge"] = 15,
					["Esteldin"] = 21, ["Feste Guruth"] = 15 } },
		["0DAF4"] = { N="Grosser Fingerknochen", H={ [27]="TE" },
				L = { ["Feste Guruth"] = 15 } },
		["0DB63"] = { N="Grosser Flügel", H={ [20]="MB", [22]="TE", [26]="RE,TH" },
				L = { ["Verlassene Herberge"] = 15, ["Othrikar"] = 21,
					["Esteldin"] = 21, ["Schragen"] = 20 } },
		["0DB1B"] = { N="Ledernes Fell", H={ [28]="RE", [30]="MS", [33]="WA" },
				L = { ["Esteldin"] = 21, ["Tinnudir"] = 25, ["Hafergut"] = 25 } },
		["0DAE3"] = { N="Todbringende Klaue", H={ [38]="--", [41]="--" },
				L = { ["Tyrn Lhuig"] = 41, ["Aughaire"] = 38 } },
		["0DC47"] = { N="Leichter Panzer", H={ [9]="MS", [11]="TH" },
				L = { ["Hobbingen"] = 6, ["Gondamon"] = 6 } },
		["2770C"] = { N="Gekennzeichnetes Fell", H={ [71]="TR", [75]="RS", [80]="--" },
				L = { ["Kundschafterlager der Rohirrim"] = 71, ["Grimbolds Lager"] = 71,
					["Voranbront"] = 71, ["Großer Fluss"] = 75, ["Ost-Rohan"] = 80 } },
		["0DBD0"] = { N="Matte Feder", H={[9]="TH" },
				L = { ["Gondamon"] = 6 } },
		["0DB21"] = { N="Mattes Fell", H={ [8]="MS", [9]="TH" },
				L = { ["Hobbingen"] = 6, ["Gondamon"] = 6 } },
		["0DCC6"] = { N="Matte Tierhaut", H={ [9]="MS", [10]="TH" },
				L = { ["Hobbingen"] = 6, ["Gondamon"] = 6 } },
		["27721"] = { N="Metallene Schwertscheide", H={ [65]="MD" },
				L = { ["Galtrev"] = 65,  ["Lhan Tarren"] = 65,
					["Avardin"] = 65, ["Barnavon"] = 65 } },
		["3F1EA"] = { N="Verfaulte Haut", H={ [105]="RR" },
				L = { ["Weites Anorien"] = 105 } },
		["0DB86"] = { N="Monströses Ohr", H={ [46]="LF", [48]="--" },
				L = { ["Echad Dunann"] = 41, ["Suri-kylä"] = 36 } },
		["0DAEF"] = { N="Monströser Dreck", H={ [46]="--", [47]="CN" },
				L = { ["Gath Forthnir"] = 47, ["Gwingris"] = 41 } },
		["0DBAF"] = { N="Monströser Schleim", H={ [47]="--" },
				L = { ["Gwingris"] = 41 } },
		["0DD58"] = { N="Monströses Kernholz", H={ [47]="--" },
				L = { ["Gwingris"] = 41 } },
		["0DB68"] = { N="Monströser Flügel", H={ [47]="--", [48]="CN,--" },
				L = { ["Gwingris"] = 41, ["Echad Dunann"] = 41, ["Gath Forthnir"] = 48 } },
		["30478"] = { N="Bemooster Ast", H={ [85]="PW" },
				L = { ["Forlach"] = 85 } },
		["0DC3D"] = { N="Bemooster Panzer", H={ [15]="MB" },
				L = { ["Bree"] = 15 } },
		["2771C"] = { N="Dreckiger Dreck", H={ [68]="MD" },
				L = { ["Galtrev"] = 68,  ["Lhan Tarren"] = 68,
					["Avardin"] = 68, ["Barnavon"] = 68 } },
		["0DC57"] = { N="Gedämpfter Staub", H={ [34]="WA" },
				L = { ["Tinnudir"] = 25 } },
		["0DEAA"] = { N="Garstiger Dreck", H={ [57]="IG" },
				L = { ["Einundzwanzigste Halle"] = 57, ["Überschattete Zuflucht"] = 57,
					["Anazarmekhem"] = 57, ["Die Ork-Wacht"] = 57, ["Erste Halle"] = 57 } },
		["0DCCC"] = { N="Neue Schwertscheide", H={ [35]="ER,--,TH" },
				L = { ["Feste Forod"] = 25, ["Barachens Lager"] = 22, ["Echad Candelleth"] = 22 } },
		["3A79C"] = { N="Verschnörkeltes Ohr", H={ [85]="Eo" },
				L = { ["West-Rohan"] = 86 } },
		["30489"] = { N="Verschnörkelte Schwertscheide", H={ [80.1]="--", [85]="PW" },
				L = { ["Ost-Rohan"] = 80, ["Forlach"] = 85 } },
		["0DAF3"] = { N="Angefressener Fingerknochen", H={ [19]="MB" },
				L = { ["Bree"] = 19 } },
		["3A797"] = { N="Zerfressene Schwertscheide", H={ [85]="He", [100]="DA,DM,Pe,RI" },
				L = { ["West-Rohan"] = {l=81,r='He'}, ["West-Gondor"] = 90,
					["Zentrum Gondors"] = 100, ["Ost-Gondor"] = 100, ["Alt-Anorien"] = 100 } },
		["0DEC6"] = { N="Polierte Schuppe", H={ [53]="IG" },
				L = { ["Delfblick"] = 53, ["Tiefer Abgrund"] = 53, ["Jazargund"] = 53,
					["Der verrottende Keller"] = 53, ["Kammer des Scheidewegs"] = 53 } },
		["0DFC2"] = { N="Polierte Schwertscheide", H={ [53]="IG" },
				L = { ["Delfblick"] = 53, ["Tiefer Abgrund"] = 53, ["Jazargund"] = 53,
					["Der verrottende Keller"] = 53, ["Kammer des Scheidewegs"] = 53 } },
		["0DEEA"] = { N="Polierter Flügel", H={ [49]="--" },
				L = { ["Echad Mirobel"] = 41 } },
		["0DC30"] = { N="Wuchtiger Ast", H={ [46]="--" },
				L = { ["Gwingris"] = 41 } },
		["27735"] = { N="Prismatische Schuppe", H={ [75]="RS" },
				L = { ["Großer Fluss"] = 75 } },
		["27710"] = { N="Durchstochener Schild", H={ [71]="TR", [75]="RS", [80]="--" },
				L = { ["Kundschafterlager der Rohirrim"] = 71, ["Grimbolds Lager"] = 71,
					["Voranbront"] = 71, ["Großer Fluss"] = 75, ["Ost-Rohan"] = 80 } },
		["0DB1E"] = { N="Tiefschwarzes Fell", H={ [42]="LF,--", [43]="LF,TH", [44]="--" },
				L = { ["Zigilgund"] = 36,  ["Hrimbarg"] = 38, ["Pynti-peldot"] = 36,
					["Kauppa-kohta"] = 36, ["Gabilshathur"] = 44, ["Aughaire"] = 42 } },
		["0DCC3"] = { N="Tiefschwarze Tierhaut", H={ [44]="LF,TH", [45]="LF,--", [46]="--" },
				L = { ["Zigilgund"] = 36, ["Hrimbarg"] = 38, ["Pynti-peldot"] = 36,
					["Aughaire"] = 43, ["Kauppa-kohta"] = 36, ["Gabilshathur"] = 46,
					["Suri-kylä"] = 36, ["Tyrn Lhuig"] = 41 } },
		["0DEA4"] = { N="Kratzende Klaue", H={ [57]="IG" },
				L = { ["Einundzwanzigste Halle"] = 57, ["Überschattete Zuflucht"] = 57,
					["Anazarmekhem"] = 57, ["Die Ork-Wacht"] = 57, ["Erste Halle"] = 57 } },
		["0DAE4"] = { N="Messerscharfe Klaue", H={ [45]="--" },
				L = { ["Gabilshathur"] = 45 } },
		["0DAF6"] = { N="Wulstiger Fingerknochen", H={ [35]="--" },
				L = { ["Thorenhad"] = {l=22,r='--'} } },
		["30481"] = { N="Zerfetzter Umhang", H={ [80.1]="--", [85]="PW" },
				L = { ["Ost-Rohan"] = 80, ["Forlach"] = 85 } },
		["3A74D"] = { N="Raue Haut", H={ [85]="Eo" },
				L = { ["West-Rohan"] = 85 } },
		["0DBC9"] = { N="Zerzauste Feder", H={ [25]="TE", [27]="RE", [28]="TH" },
				L = { ["Othrikar"] = 21, ["Feste Guruth"] = 15, ["Esteldin"] = 21 } },
		["0DB82"] = { N="Narbiges Ohr", H={ [28]="RE", [30]="MS", [32]="WA" },
				L = { ["Tinnudir"] = 25, ["Hafergut"] = 25, ["Esteldin"] = 21 } },
		["0DD53"] = { N="Narbiges Kernholz", H={ [26]="RE", [28]="TE" },
				L = { ["Agamaur"] = 15, ["Meluinen"] = 21 } },
		["0DBFE"] = { N="Narbiger Schwanz", H={ [30]="RE" },
				L = { ["Esteldin"] = 21 } },
		["0DAE0"] = { N="Scharfe Klaue", H={ [24]="RE" },
				L = { ["Meluinen"] = 21 } },
		["30497"] = { N="Scharfe Schuppe", H={ [80]="--" },
				L = { ["Ost-Rohan"] = 80 } },
		["3047D"] = { N="Zerschmetterte Keule", H={ [80]="--" },
				L = { ["Ost-Rohan"] = 80 } },
		["3A72A"] = { N="Zerschmetterter Dolch", H={ [85]="Eo" },
				L = { ["West-Rohan"] = 85 } },
		["3A729"] = { N="Zerschmettertes Beil", H={ [85]="He", [100]="DA,Pe,RI" },
				L = { ["West-Rohan"] = {l=81,r='He'},
					["West-Gondor"] = 90, ["Zentrum Gondors"] = 100, ["Ost-Gondor"] = 100 } },
		["3F1E1"] = { N="Zersplitterter Speer", H={ [105]="RR" },
				L = { ["Weites Anorien"] = 105 } },
		["0DB97"] = { N="Brillante Essenz", H={ [30]="TE", [30.1]="WA" },
				L = { ["Agamaur"] = 15, ["Tinnudir"] = 25 } },
		["3A74A"] = { N="Glänzender Panzer", H={ [100]="DM,Pe" },
				L = { ["Zentrum Gondors"] = 100, ["Alt-Anorien"] = 100 } },
		["0DAEC"] = { N="Seidiger Dreck", H={ [35]="ER,--" },
				L = { ["Echad Candelleth"] = 22, ["Thorenhad"] = {l=22,r='--'} } },
		["30498"] = { N="Seidiges Fell", H={ [80]="--" },
				L = { ["Ost-Rohan"] = 80 } },
		["0DB1D"] = { N="Geschmeidiges Fell", H={ [37]="--", [39]="--" },
				L = { ["Aughaire"] = 39, ["Gloins Lager"] = 37, ["Hohe Klippe"] = 37 } },
		["0DCC2"] = { N="Geschmeidige Tierhaut", H={ [38]="--", [40.1]="--" },
				L = { ["Gloins Lager"] = 38, ["Hohe Klippe"] = 38, ["Aughaire"] = 40 } },
		["30494"] = { N="Schleimiger Dreck", H={ [85]="PW" },
				L = { ["Forlach"] = 85 } },
		["0DB26"] = { N="Glatte Schuppe", H={ [35]="ER" },
				L = { ["Echad Candelleth"] = 22 } },
		["0DB65"] = { N="Glatter Flügel", H={ [35]="ER" },
				L = { ["Thorenhad"] = 22 } },
		["0DCC0"] = { N="Weiche Tierhaut", H={ [29]="MS,RE", [33]="WA" },
				L = { ["Tinnudir"] = 25, ["Esteldin"] = 21, ["Hafergut"] = 25 } },
		["27725"] = { N="Funkelnder Staub", H={ [75]="RS" },
				L = { ["Großer Fluss"] = 75 } },
		["27733"] = { N="Gesprenkeltes Ohr", H={ [71]="TR", [75]="RS", [80]="--" },
				L = { ["Kundschafterlager der Rohirrim"] = 71, ["Grimbolds Lager"] = 71,
					["Voranbront"] = 71, ["Großer Fluss"] = 75, ["Ost-Rohan"] = 80 } },
		["3048A"] = { N="Gespaltener Ast", H={ [80]="--" },
				L = { ["Ost-Rohan"] = 80 } },
		["27720"] = { N="Geflecktes Ohr", H={ [65]="MD" },
				L = { ["Galtrev"] = 65,  ["Lhan Tarren"] = 65,
					["Avardin"] = 65, ["Barnavon"] = 65 } },
		["0DFBC"] = { N="Gefleckte Tierhaut", H={ [53]="IG" },
				L = { ["Delfblick"] = 53, ["Tiefer Abgrund"] = 53, ["Jazargund"] = 53,
					["Der verrottende Keller"] = 53, ["Kammer des Scheidewegs"] = 53 } },
		["0DBB1"] = { N="Schmieriger Schleim", H={ [12]="MS,TH" },
				L = { ["Hobbingen"] = 6, ["Gondamon"] = 6 } },
		["30492"] = { N="Befleckte Tierhaut", H={ [80]="--" },
				L = { ["Ost-Rohan"] = 80 } },
		["0DAEB"] = { N="Klebriger Dreck", H={ [29]="RE", [30]="MS", [33]="WA" },
				L = { ["Esteldin"] = 21, ["Hafergut"] = 25, ["Tinnudir"] = 25 } },
		["2771A"] = { N="Klebriger Schleim", H={ [75]="RS" },
				L = { ["Großer Fluss"] = 75 } },
		["27730"] = { N="Gestreckte Tierhaut", H={ [65]="MD" },
				L = { ["Galtrev"] = 65,  ["Lhan Tarren"] = 65,
					["Avardin"] = 65, ["Barnavon"] = 65 } },
		["30488"] = { N="Stummeliger Schnabel", H={ [80]="--" },
				L = { ["Ost-Rohan"] = 80 } },
		["0DCCD"] = { N="Nietenbesetzte Schwertscheide", H={ [38]="WA", [39]="--", [40.1]="--" },
				L = { ["Aughaire"] = 40, ["Gloins Lager"] = 38,
					["Hohe Klippe"] = 38, ["Annuminas"] = 33 } },
		["30499"] = { N="Angelaufene Waffenscheide eines Schwertes", H={ [80]="--" },
				L = { ["Ost-Rohan"] = 80 } },
		["3A753"] = { N="Zerrissenes Fell", H={ [85]="Eo" },
				L = { ["West-Rohan"] = 85 } },
		["3048E"] = { N="Zerfetzte Tierhaut", H={ [85]="PW" },
				L = { ["Forlach"] = 85 } },
		["27736"] = { N="Dicker Ast", C=3, H={ [75]="HL" },
				L = { ["Großer Fluss"] = {l=68,r='HL'} } },
		["27734"] = { N="Dicker Bürzel", H={ [75]="RS" },
				L = { ["Großer Fluss"] = 75 } },
		["3A79A"] = { N="Verdickter Schleim", H={ [100]="DM" },
				L = { ["Alt-Anorien"] = 100 } },
		["3A755"] = { N="Dünner Flügel", H={ [85]="Eo" },
				L = { ["West-Rohan"] = 85 } },
		["3047B"] = { N="Gefärbter Panzer", H={ [80]="--" },
				L = { ["Ost-Rohan"] = 80 } },
		["3A757"] = { N="Zerrissene Haut", H={ [85]="He", [100]="DA,DM,Pe,RI" },
				L = { ["West-Rohan"] = {l=81,r='He'}, ["West-Gondor"] = 90,
					["Zentrum Gondors"] = 100, ["Ost-Gondor"] = 100, ["Alt-Anorien"] = 100 } },
		["0DC2B"] = { N="Robuster Ast", H={ [28]="TE" },
				L = { ["Agamaur"] = 15 } },
		["0DC40"] = { N="Robuster Panzer", H={ [23]="TE", [24]="RE", [25]="RE", [26]="TE" },
				L = { ["Meluinen"] = 21, ["Verlassene Herberge"] = 15,
					["Esteldin"] = 21, ["Feste Guruth"] = 15 } },
		["0DCCA"] = { N="Robuste Schwertscheide", H={ [23]="MB", [24]="RE,TE", [25]="RE", [27]="TH" },
				L = { ["Meluinen"] = 21, ["Amon Raith"] = 21, ["Othrikar"] = 21,
					["Schragen"] = 21, ["Feste Guruth"] = 15 } },
		["0DC43"] = { N="Harter Panzer", H={ [37]="TH", [39]="--" },
				L = { ["Hohe Klippe"] = 37, ["Gloins Lager"] = 37, ["Aughaire"] = 39 } },
		["3A759"] = { N="Giftiger Dreck", H={ [100]="DA,RI" },
				L = { ["West-Gondor"] = 90, ["Ost-Gondor"] = 100 } },
		["3048F"] = { N="Zerzaustes Fell", H={ [80.1]="--", [85]="PW" },
				L = { ["Ost-Rohan"] = 80, ["Forlach"] = 85 } },
		["0DC23"] = { N="Sehr scharfer Schnabel", H={ [35]="ER" },
				L = { ["Thorenhad"] = 22 } },
		["0DAE1"] = { N="Sehr scharfe Klaue", H={ [28]="MS", [31]="WA" },
				L = { ["Hafergut"] = 25, ["Tinnudir"] = 25 } },
		["30473"] = { N="Verwitterter Schnabel", H={ [80.1]="--", [85]="PW" },
				L = { ["Ost-Rohan"] = 80, ["Forlach"] = 85 } },
		["0DB17"] = { N="Nasses Fell", H={ [14]="MB" },
				L = { ["Bree"] = 14 } },
		["0DCBC"] = { N="Nasse Tierhaut", H={ [15]="MB" },
				L = { ["Bree"] = 15 } },
		["3F1E0"] = { N="Abgetragene Fell", H={ [105]="RR" },
				L = { ["Weites Anorien"] = 105 } },
		["0DCC7"] = { N="Abgenutzte Schwertscheide", H={ [15]="MB" },
				L = { ["Bree"] = 15 } },
	},
	inf = {
		["Durchsetzter Granat"] = "135D7",
		["Durchsetzter Saphir"] = "135D8",
		["Durchsetzter Adamant"] = "135D9",
	},
	mob = {
		{ n="Ancient Bile-spewer", l=28, z="LL", i={"0DCCA","0F791","0DB96"} },
		{ n="Ancient Bog-warden", l=29, z="LL", i={"0DAF4","0F791","0DCCA","0DCCB","0DAF5","0F792"} },
		{ n="Angmarim Invader", l=47, z="F", i={"0F795","0F796","0DCCE","0DCCF"} },
		{ n="Angmarim Raider", l=47, z="F", i={"0F795","0DCCE"} },
		{ n="Angmarim Scout", l=47, z="F", i={"0F795","0F796","0DCCF","0F797"} },
		{ n="Angmarim Soldier", l=52, z="Er", i={"0F797"} },
		{ n="Bale-fang Barghest", l=47, z="A", i={"0DB1E","0DB1F","0DCC4","0DB86"} },
		{ n="Barkshredder Cub", l=15, z="BL", i={"0DB17","0DCBC"} },
		{ n="Barrow-bat", l=20, z="BL", i={"0DB61","0DCBD","0DB80"} },
		{ n="Barrow-candle", l=20, d=-1, z="BL", i={"0DB94"} },
		{ n="Barrow-spider", l=20, z="BL", i={"0DC3E","0DAE9","0DBA9"} },
		{ n="Barrow-spirit", l=20, d=3, z="BL", i={"0F78F","0DAF3"} },
		{ n="Barrow-warden", l=20, d=3, z="BL", i={"0DCCD"} },
		{ n="Barrow-wight", l=20, z="BL", i={"0F78F","0DAF3"} },
		{ n="Barrow-wight Archer", l=18, z="BL", i={"0F78F","0DAF3","0DB94"} },
		{ n="Barrow-wight Warrior", l=18, z="BL", i={"0F78F","0DAF3","0DCC8"} },
		{ n="Bile-spewer Marksman", l=28, z="LL", i={"0DAF4","0F791"} },
		{ n="Bindbole Spinner", l=10, z="S", i={"0DAF1"} },
		{ n="Bindbole Weaver", l=10, z="S", i={"0DBB1","0DAF1","0DC47"} },
		{ n="Biting Field-rat", l=18, d=-1, z="BL", i={"0DADE","0DCBD"} },
		{ n="Biting Neeker-breeker", l=15, z="BL", i={"0DC3D"} },
		{ n="Biting Sand-flies", l=31, d=-1, z="E", i={"0DAEB","0DBAB"} },
		{ n="Biting Shrew", l=6, z="S", i={"0DCC6"} },
		{ n="Black-bear Mauler", l=79, z="ER", i={"30492","30498","2772A","2770C"} },
--		{ n="Blade-beak Burrower", l=51, z="A", i={"xx"} },
		{ n="Blade-beak Digger", l=47, z="A", i={"0DAE4","0DCC3","0DC01"} },
		{ n="Blade-beak Scythe", l=47, z="A", i={"0DAE4","0DCC3","0DC01"} },
		{ n="Bloated Brimstone-leech", l=47, z="A", i={"0DAEF","0DBAF","0DAEE"} },
		{ n="Bloated Muck-crawler", l=29, d=-1, z="LL", i={"0DAEA","0DC43","0DAEB","0DC41"} },
		{ n="Blogmal Defender", l=49, z="MM", i={"0F796","0DCCF"} },
		{ n="Blogmal Fighter", l=48, z="MM", i={"0F796","0DCCF"} },
		{ n="Blue-crag Defiler", l=8, z="EL", i={"0F79E","0DCD1"} },
		{ n="Blue-crag Novice", l=9, z="EL", i={"0F79E"} },
		{ n="Blue-crag Piercer", l=7, z="EL", i={"0F79E","0DCD1"} },
		{ n="Blue-crag Sentinel", l=8, z="EL", i={"0F79E","0DCD1"} },
		{ n="Bog-fly Hatcher", l=29, z="LL", i={"0DAEB","0DC41","0DAEA","0DC43"} },
		{ n="Bog-fly Hatchling", l=29, z="LL", i={"0DAEA","0DC43","0DBAA"} },
		{ n="Bog-prowler Ambusher", l=28, z="LL", i={"0DC40","0DD53"} },
		{ n="Bog-toad", l=8, z="S", i={"0DCC6","0DAE7"} },
		{ n="Bog-warden Archer", l=29, z="LL", i={"0F791","0DAF4","0DAF5","0DCCB","0F792","0DB97"} },
		{ n="Bogbereth Creeper", l=48, z="A", i={"0DC45","0DAEF","0DBAF"} },
		{ n="Bogbereth Egg-tender", l=50, z="A", i={"0DAEF","0DBAF"} },
		{ n="Bogbereth Lurker", l=48, z="A", i={"0DC45","0DAEF","0DBAF"} },
		{ n="Blighted Mountain-bear", l=39, z="T", i={"0DB1D","0DB83","0DB84"} },
		{ n="Broken-tusk Scrubrunner", l=22, z="LL", i={"0DCBD"} },
		{ n="Brush Hunter", l=25, z="LL", i={"0DB1A"} },
		{ n="Burrowing Sand-norbog", l=30, z="E", i={"0DC41","0DAE1"} },
		{ n="Burrowing Shrew", l=9, d=-1, z="S", i={"0DB21","0DB88"} },
		{ n="Buzzing Gnats", l=7, z="S", i={"0DAF1","0DC47"} },
		{ n="Buzzing Swamp-fly", l=43, z="A", i={"0DAED","0DAEE","0DC44"} },
		{ n="Camouflaged Bog-prowler", l=30, z="LL", i={"0DC41"} },
--		{ n="Cave Hendroval", l=46, d=1, z="EL", i={"xx"} },
		{ n="Cave Snow-beast", l=50, z="Er", i={"0DB1F","0DCC4","0DB86"} },
		{ n="Celebrant Brigand", l=75, z="GR", i={"27710","27724"} },
		{ n="Clawing Barghest", l=22, z="ND", i={"0DCBD","0DB80"} },
		{ n="Clawing Rock-worm", l=39, z="T", d=3, i={"0DB27","0DCC2"} },
		{ n="Clawing Rock-worm;2", l=48, z="Er", i={"0DCC4"} },
		{ n="Cliff Hendroval", l=11, z="EL", i={"0DB6A","0DBD0","0DC28"} },
		{ n="Conscripted Defender", l=54, z="M", i={"0F797"} },
		{ n="Conscripted Keeper", l=54, z="M", i={"0F797"} },
		{ n="Corcur Blood-sworn", l=41, z="MM", i={"0DCCD"} },
		{ n="Corcur Skirmisher", l=38, z="T", i={"0F793","0F794","0DCCD","0DCCC"} },
		{ n="Corrupt Darkclaw", l=33, d=1, z="T", i={"0DCC0"} },
		{ n="Corrupted Norboglir", l=47, z="A", i={"0DC44","0DAE4","0DC45"} },
		{ n="Craban Scout", l=19, d=1, z="BL", i={"0DB61","0DC1F"} },
		{ n="Crawling Fire-worm", l=47, z="A", i={"0DB28","0DCC4","0DCC3"} },
		{ n="Crawling Rock-worm", l=42, z="T", d=3, i={"0DB27","0DCC2"} },
		{ n="Crazed Shadow-warg", l=50, z="Er", i={"0DB1F"} },
		{ n="Crazed Stonehold", l=21, z="ND", i={"0F78F","0DCC8"} },
		{ n="Creeping Barrow-crawler", l=18, z="BL", i={"0DAE9","0DC3E"} },
		{ n="Creeping Hand", l=20, d=1, z="BL", i={"0DAF3"} },
		{ n="Creeping Sand-lurker", l=31, z="E", i={"0DC41","0DD54"} },
		{ n="Creoth Apprentice", l=32, d=3, z="LL", i={"0F792","0DCCB"} },
		{ n="Creoth Chieftain", l=32, d=4, z="LL", i={"0F792"} },
		{ n="Creoth Disciple", l=32, d=3, z="LL", i={"0F792"} },
		{ n="Creoth Leader", l=32, d=4, z="LL", i={"0F792"} },
		{ n="Cruel-beak Sentry", l=21, d=1, z="ND", i={"0DB61"} },
		{ n="Curious Bear", l=17, z="BL", i={"0DCBC","0DB17"} },
		{ n="Cunning Hunting Hound", l=74, z="D", i={"2772A","2770C","27733"} },
		{ n="Curious Láthbear", l=79, z="ER", i={"30492","30498","2772A"} },
		{ n="Curr-olog", l=43, d=4, z="MM", i={"0DCCE","0DCCD"} },
--		{ n="Draig-lûth Ambusher", l=71, z="D", i={"2770F","27710","27721"} },
--		{ n="Draig-lûth Archer", l=71, z="D", i={"2770F","27710","27721"} },
--		{ n="Draig-lûth Warrior", l=71, z="D", i={"2770F","27710","27721"} },
		{ n="Dark-wing Scout", l=48, d=1, z="Er", i={"0DB68"} },
		{ n="Dark-wing Spy", l=50, d=1, z="Er", i={"0DEEA","0DB68"} },
		{ n="Deadly Blight-worm", l=38, z="T", i={"0DB27","0DCC1","0DCC2"} },
		{ n="Deadly Bile-spewer", l=28, z="LL", i={"0DCCA","0F791","0DB96","0DAF4"} },
		{ n="Deadly Ironscale", l=43, d=4, z="A", i={"0DAE3","0DAE4","0DC24","0DCC2"} },
		{ n="Deadly Wight", l=32, d=4, z="LL", i={"0DAF5","0DCCB"} },
		{ n="Decaying Barrow-wight", l=20, z="BL", i={"0F78F","0DB94","0DAF3","0DB96"} },
--		{ n="Decaying Hand", l=48, d=-1, z="A", i={"xx"} },
		{ n="Deep-claw Digger", l=53, z="M", i={"0DEA2"} },
		{ n="Deep-claw Gnasher", l=52, z="M", i={"0DEC6","0DFBC"} },
		{ n="Deeps Glow-worm", l=52, d=1, z="M", i={"0DEA8"} },
		{ n="Diseased Dragonet", l=52, z="M", i={"0DEA2","0DFBC"} },
		{ n="Dourhand Blaster", l=46, z="EL", i={"0DCCE","0F795"} },
		{ n="Dourhand Captain", l=47, z="F", i={"0F795","0DCCE"} },
		{ n="Dourhand Excavator", l=46, z="EL", i={"0DCCE","0F795"} },
		{ n="Dourhand Hunter", l=8, z="S", i={"0F79E","0DCD1"} },
		{ n="Dourhand Looter", l=46, z="F", i={"0F795","0DCCE"} },
		{ n="Dourhand Miner", l=46, z="F", i={"0F795","0DCCE"} },
		{ n="Dourhand Trapper", l=8, z="S", i={"0F79E","0DCD1"} },
		{ n="Downs Wildcat", l=28, z="ND", i={"0DCBF","0DB1A","0DB81"} },
		{ n="Draig-luth Archer", l=72, z="D", i={"2770F"} },
		{ n="Draig-luth Captain", l=72, d=3, z="D", i={"2770F","27721"} },
		{ n="Draig-luth Rider", l=72, z="D", i={"2770F","27721"} },
		{ n="Draig-luth Shieldbearer", l=72, z="D", i={"2770F","27721"} },
		{ n="Dun Neeker-breeker", l=12, z="BL", i={"0DC3D","0DC47"} },
		{ n="Dunlending Brawler", l=51, z="Er", i={"0F797"} },
		{ n="Dunlending Guard", l=48, z="Er", i={"0F796","0DCCF"} },
		{ n="Dunlending Labourer", l=48, z="Er", i={"0F796","0DCCF"} },
		{ n="Dunlending Lookout", l=50, z="Er", i={"0F796","0F792"} },
		{ n="Dunlending Raider", l=74, z="D", i={"27724","27710"} },
		{ n="Dunlending Scout", l=52, z="Er", i={"0F797"} },
		{ n="Dunlending Scrapper", l=51, z="Er", i={"0F797"} },
		{ n="Dunlending Soldier", l=50, z="Er", i={"0F796","0DCCF"} },
		{ n="Dunlending Tracker", l=52, z="Er", i={"0F797"} },
		{ n="Dusk-hound", l=72, z="D", i={"27720","27730"} },
		{ n="Duvardain Blood-seer", l=47, z="A", i={"0DCCE","0F795"} },
		{ n="Duvardain Protector", l=47, z="A", i={"0F796","0DCCF","0F795"} },
		{ n="Eastemnet Boar", l=82, z="ER", i={"30492","3048E","3048C"} },
		{ n="Elder Moor-stalker", l=36, z="T", i={"0DB1C","0DB83","0DCC1"} },
		{ n="Elder Moria-rider", l=52, z="M", i={"0F797"} },
		{ n="Elder Stonehoof", l=33, z="T", i={"0DCC0"} },
		{ n="Enslaved Pale-folk", l=50, z="A", i={"0F796"} },
		{ n="Fanged-stalker", l=50, z="Er", i={"0DCC4","0DB1F"} },
		{ n="Fell Bog-prowler", l=30, z="LL", i={"0DC41"} },
		{ n="Fell Holly-tender", l=48, z="Er", i={"0DC45","0DD58"} },
		{ n="Fell Wight", l=32, d=4, z="LL", i={"0DAF5","0F792","0DCCB"} },
		{ n="Feral Tusker", l=49, z="Er", i={"0DCC4"} },
		{ n="Field-bear", l=15, z="BL", i={"0DCBC","0DB17"} },
		{ n="Flickering Limrafn", l=32, d=-1, z="E", i={"0DC57","0DB97"} },
		{ n="Flittering Gloom-wing", l=15, d=-1, z="BL", i={"0DCBC"} },
		{ n="Flitting Bat", l=10, d=1, z="S", i={"0DCC6","0DB6A"} },
		{ n="Forest Biter", l=16, z="BL", i={"0DAE8","0DC3D"} },
		{ n="Foul Blade-beak", l=50, z="A", i={"0DCC4"} },
		{ n="Freezing Grim", l=50, z="Er", i={"0DAEF"} },
		{ n="Frost-worm", l=46, z="F", i={"0DB28","0DC01","0DCC3"} },
		{ n="Fugitive Tomb-robber", l=33, z="E", i={"0F792"} },
		{ n="Gabilazan Guard", l=42, z="MM", i={"0F794","0DCCD"} },
		{ n="Gaunt Plague-bearer", l=20, d=3, z="BL", i={"0DCC8","0F78F"} },
		{ n="Gauradan Far-seer", l=43, z="T", i={"0DCCE","0F795","0DCCD"} },
		{ n="Gauradan Forest-walker", l=44, z="T", i={"0DCCE","0F795"} },
		{ n="Gauradan Hunter", l=46, z="F", i={"0F795","0DCCE"} },
		{ n="Gauradan Ravager", l=48, z="F", i={"0F796","0DCCE"} },
		{ n="Gauradan Stalker", l=48, z="F", i={"0F796","0DCCE"} },
		{ n="Gauradan Thief", l=46, z="F", i={"0F795","0DCCE"} },
		{ n="Gauradan Wind-master", l=46, z="MM", i={"0F795","0DCCE"} },
		{ n="Gauradan Wolf-born", l=46, z="MM", i={"0DCCE"} },
		{ n="Gelid Grim", l=50, z="F", i={"0DAEF"} },
		{ n="Giant Rock-thrower", l=39, d=4, z="T", i={"0F794"} },
		{ n="Giant Snow-bear", l=43, z="MM", i={"0DB1E","0DCC3","0DCC2","0DB1D"} },
		{ n="Giant Stone-breaker", l=39, d=4, z="T", i={"0F794"} },
		{ n="Glen-buck", l=35, z="T", i={"0DB1C","0DCC1"} },
		{ n="Glen-hind", l=35, d=-2, z="T", i={"0DB1C","0DCC1","0DB83"} },
--		{ n="Glimmering Limrafn", l=37, d=-1, z="E", i={"xx"} },
		{ n="Glowing Fire-fly", l=48, z="Er", i={"0DAEF","0DC45","0DBAF"} },
		{ n="Goblin-town Cook", l=48, z="MM", i={"0F796"} },
		{ n="Goblin-town Delver", l=48, z="MM", i={"0F796","0DCCF"} },
		{ n="Goblin-town Drudger", l=48, d=1, z="MM", i={"0F795","0DCCE","0DCCF"} },
		{ n="Goblin-town Guard", l=48, z="MM", i={"0F796","0DCCF"} },
		{ n="Goblin-town Jailor", l=48, z="MM", i={"0F796","0DCCF"} },
		{ n="Goblin-town Keeper", l=49, z="MM", i={"0F796","0DCCF"} },
		{ n="Goblin-town Lickspittle", l=47, z="MM", i={"0F796","0DCCF"} },
		{ n="Goblin-town Lobber", l=50, z="A", i={"0F796","0DCCF"} },
		{ n="Goblin-town Ravager", l=48, z="MM", i={"0DB1F","0DCC4","0DB86"} },
		{ n="Goblin-town Runner", l=49, z="MM", i={"0DCCF","0F796"} },
		{ n="Goblin-town Shadow-skulker", l=50, z="A", i={"0F796","0F792"} },
		{ n="Goblin-town Stalker", l=47, z="MM", i={"0DB1E","0DCC3","0DB1F"} },
		{ n="Goblin-town Warrior", l=48, z="MM", i={"0F796"} },
		{ n="Goblin-town Worker", l=47, z="MM", i={"0F795","0DCCF","0DCCE"} },
		{ n="Gore-crow Watcher", l=25, d=1, z="LL", i={"0DB63","0DC21"} },
		{ n="Gramsfoot Guard", l=11, z="S", i={"0F79E","0DCD1"} },
		{ n="Gramsfoot Hurler", l=11, z="S", i={"0F79E","0DCD1"} },
		{ n="Grasping Holly-tender", l=48, z="Er", i={"0DC45","0DD58"} },
		{ n="Grasping Sand-lurker", l=31, z="E", i={"0DC41","0DD54"} },
		{ n="Great Brown Bat", l=12, d=1, z="S", i={"0DB6A","0DB88","0DCC6","0DCBC"} },
		{ n="Grodbog Worker", l=52, z="M", i={"0DEA8"} },
--		{ n="Winter-worm", l=47, d=3, z="F", i={"0DB28","0DCC3"} },
		{ n="Greenfields Biter", l=11, z="S", i={"0DAF1","0DC47","0DBB1"} },
		{ n="Greenfields Queen", l=13, z="S", i={"0DAE8","0DC3D"} },
		{ n="Greenfields Tree-weaver", l=12, z="S", i={"0DAF1","0DC47","0DBB1"} },
		{ n="Greensward-hart", l=33, z="E", i={"0DCC0","0DB1B"} },
		{ n="Grim Creoth", l=32, d=3, z="LL", i={"0F792"} },
		{ n="Grim Wight", l=30, z="LL", i={"0DAF5","0DCCB","0F792"} },
		{ n="Grimclaw Chill-wind", l=9, z="EL", i={"0DB6A"} },
		{ n="Greater Sickle-fly", l=14, z="BL", i={"0DC3D","0DAE8"} },
		{ n="Green Neeker-breeker", l=12, z="BL", i={"0DC3D","0DC47"} },
		{ n="Half-orc Ambusher", l=75, z="NC", i={"27724","27710"} },
		{ n="Half-orc Archer", l=88, z="ER", i={"30489","3A799","3A72A"} },
		{ n="Half-orc Captain", l=52, z="Er", i={"0DCCF","0F796"} },
		{ n="Half-orc Guard", l=48, z="Er", i={"0DCCF","0F796","0F797"} },
		{ n="Half-orc Hunter", l=51, z="Er", i={"0DCCC"} },
		{ n="Half-orc Leader", l=49, z="Er", i={"0DCCF","0F796"} },
		{ n="Half-orc Scout", l=49, z="Er", i={"0F796","0DCCF"} },
		{ n="Half-orc Sentry", l=75, z="NC", i={"27724","27710"} },
		{ n="Half-orc Scrapper", l=51, z="Er", i={"0DCCF","0F796","0F797"} },
		{ n="Half-orc Skirmisher", l=48, z="Er", i={"0DCCF","0F796"} },
		{ n="Half-orc Thug", l=50, z="Er", i={"0DCCF","0F796"} },
		{ n="Half-orc Tough", l=52, z="Er", i={"0F797"} },
		{ n="Half-orc Warg-keeper", l=51, z="Er", i={"0DCCF","0F796","0F797"} },
		{ n="Half-orc Wolf-keeper", l=50, z="Er", i={"0DCCF","0F796"} },
		{ n="Hateful Ongburz", l=26, z="ND", i={"0F791"} },
		{ n="Hill-bear Cub", l=11, z="EL", i={"0DCC6"} },
		{ n="His-urdan Invader", l=75, z="GR", i={"27710","27724"} },
		{ n="Hollin Lynx", l=49, z="Er", i={"0DCC4","0DB1F"} },
--		{ n="Holly-lizard", l=50, d=1, z="Er", i={"xx"} },
		{ n="Holly-troll Elder", l=49, d=3, z="Er", i={"0F796","0DC30"} },
		{ n="Holly-troll Lobber", l=48, d=3, z="Er", i={"0F796","0DC30"} },
		{ n="Holly-troll Warrior", l=48, d=3, z="Er", i={"0F796","0DC30"} },
		{ n="Howling Barrow-hound", l=20, d=3, z="BL", i={"0DCBD","0DB80"} },
		{ n="Huge Sand-norbog", l=32, z="E", i={"0DBAB","0DAE1"} },
		{ n="Huge Snow-bear", l=42, z="MM", i={"0DCC2","0DB1D"} },
		{ n="Hungry Downs-bear", l=29, z="ND", i={"0DCBF","0DB1A","0DB1B"} },
		{ n="Hunting Dusk-hound", l=72, z="D", i={"27720","27730"} },
		{ n="Hunting North-hawk", l=28, z="ND", i={"0DB63","0DBC9","0DC21"} },
		{ n="Ice-shore Bear", l=47, z="F", i={"0DB1E","0DB1F","0DCC3","0DCC4"} },
		{ n="Ice-shore Matron", l=47, z="F", i={"0DB1E","0DB1F","0DCC3","0DCC4"} },
		{ n="Ice-shore Peikko", l=47, z="F", i={"0DB1E","0DB1F","0DCC3","0DCC4"} },
		{ n="Ice-shore Yearling", l=47, d=-2, z="F", i={"0DB1E","0DB1F","0DCC3","0DCC4"} },
		{ n="Ice-walker Captain", l=48, z="F", i={"0F796","0DCCF"} },
		{ n="Ice-wight Warrior", l=48, z="F", i={"0DCCF","0F796"} },
		{ n="Ice-wight Warrior", l=48, z="F", i={"0DCCF","0F796"} },
		{ n="Ice-worm", l=48, z="F", i={"0DCC4"} },
		{ n="Icy Plague-wind", l=50, z="F", i={"0DCCF","0F796"} },
		{ n="Iron Crown Bowman", l=44, z="A", i={"0F795","0DCCE"} },
		{ n="Iron Crown Fighter", l=44, z="A", i={"0F795"} },
		{ n="Iron Crown Marksman", l=48, z="A", i={"0F796","0DCCF"} },
		{ n="Iron Crown Messenger", l=48, z="A", i={"0F795"} },
		{ n="Iron Crown Priestess", l=49, d=3, z="A", i={"0F796"} },
		{ n="Iron Crown Tamer", l=49, z="A", i={"0F796","0DCCF"} },
		{ n="Iron Crown Warrior", l=49, z="A", i={"0DCCF"} },
		{ n="Ironbound Archer", l=48, z="A", i={"0F796","0F795","0DCCE"} },
		{ n="Ironbound Slave", l=48, z="A", i={"0F796","0F795","0DCCE"} },
		{ n="Isen Warg", l=75, z="NC", i={"2772A","2770C","27733"} },
		{ n="Isen Warg-rider", l=75, z="NC", i={"27724","27710"} },
		{ n="Isendale Goblin", l=71, z="D", i={"27721","2770F" ,"27710","27724"} },
		{ n="Isengard Goblin", l=75, z="NC", i={"27724","27710"} },
		{ n="Isengard Sticker", l=75, z="NC", i={"27724","27710"} },
		{ n="Kalpa-kita", l=45, z="F", i={"0DB1E","0DCC3"} },
		{ n="Kalpa-kita Hunter", l=45, z="F", i={"0DB1E"} },
		{ n="Kergrim Barrow-prowler", l=20, z="BL", i={"0DCBD"} },
		{ n="Kergrim Scavenger", l=37, z="E", i={"0DCC1","0DB83"} },
		{ n="Kingsfell Creeper", l=26, z="ND", i={"0DAEA","0DC40","0DBAA"} },
		{ n="Large Snow-bear", l=39, z="MM", i={"0DCC2","0DB1D","0DB84"} },
		{ n="Large Forest-hunter", l=17, z="BL", i={"0DB17","0DCBC"} },
		{ n="Lone Grey Wolf", l=10, z="EL", i={"0DB88","0DB21","0DCC6"} },
		{ n="Long-tusk Scrubrunner", l=22, z="LL", i={"0DCBD","0DB80"} },
		{ n="Luminous Fire-fly", l=48, z="Er", i={"0DAEF","0DC45"} },
		{ n="Maddened Mountain-drake", l=39, z="T", d=3, i={"0DB27","0DCC2"} },
		{ n="Maddened Razortooth", l=21, z="ND", i={"0DCBD","0DB80"} },
		{ n="Maddened Shattertusk", l=22, z="LL", i={"0DCBD"} },
		{ n="Marsh Avanc", l=75, z="GR", i={"2772A","27735","27734"} },
		{ n="Marsh Brood-watcher", l=14, z="BL", i={"0DC3D","0DAE8"} },
		{ n="Marsh Crow", l=89, z="ER", i={"3A755"} },
		{ n="Marsh Neeker-breeker", l=15, z="BL", i={"0DC3D"} },
		{ n="Marsh Spider", l=12, z="BL", i={"0DC3D","0DAE8"} },
		{ n="Mature Black-bear", l=12, z="S", i={"0DB21","0DCC6","0DB17","0DCBC"} },
		{ n="Menacing Thickjaw", l=11, z="EL", i={"0DCC6"} },
		{ n="Moor-fly Hatcher", l=33, z="T", i={"0DC41","0DAEB"} },
		{ n="Moor-stalker Scavenger", l=34, z="T", i={"0DB83","0DCC1","0DB1C"} },
		{ n="Mor-hai Defiler", l=75, z="GR", i={"27710","27724"} },
		{ n="Mor-hai Scavenger", l=75, z="GR", i={"27710","27724"} },
		{ n="Mor-hai Sentry", l=75, z="GR", i={"27710","27724"} },
		{ n="Moria Defender", l=52, z="M", i={"0F797"} },
		{ n="Moria Guard", l=53, z="M", i={"0F797"} },
		{ n="Moria Keeper", l=52, z="M", i={"0F797"} },
		{ n="Moria Overseer", l=52, z="M", i={"0F797"} },
		{ n="Moria Scout", l=53, z="M", i={"0F797"} },
		{ n="Moria Sneak", l=53, z="M", i={"0F797"} },
		{ n="Moria Soldier", l=51, z="M", i={"0F797"} },
		{ n="Morroval ", l=41, d=3, z="A", i={"0F794","0DCCD"} },
		{ n="Morroval", l=49, d=3, z="A", i={"0F796","0DCCF"} },
		{ n="Morroval-scout", l=52, z="M", i={"0F797"} },
		{ n="Mountain-bear", l=37, z="T", i={"0DB1C","0DCC1"} },
		{ n="Mountain-bear Protector", l=36, z="T", i={"0DB1C"} },
		{ n="Mountain-bear Whelp", l=35, z="T", i={"0DB1C"} },
		{ n="Neeker-breeker Burrower", l=12, z="BL", i={"0DC3D","0DBB1"} },
		{ n="Nink-hai Ravager", l=75, z="GR", i={"27710","27724"} },
		{ n="Nink-hai Scout", l=75, z="GR", i={"27710","27724"} },
		{ n="Nink-hai Sentry", l=75, z="GR", i={"27710","27724"} },
		{ n="Nink-hai Skirmisher", l=75, z="GR", i={"27710","27724"} },
		{ n="Norcrofts Field-bear", l=79, z="ER", i={"30492","30498"} },
		{ n="Norcrofts Prowler", l=78, z="ER", i={"2772A","30498"} },
		{ n="Noxious Barrow-warden", l=20, d=3, z="BL", i={"0DCCE","0DCC8"} },
		{ n="Noxious Bog-warden", l=29, z="LL", i={"0F792","0DAF5","0DAF4","0DCCA","0F791","0DCCB","0DB97"} },
		{ n="Oath-breaker Archer", l=23, z="ND", i={"0DB96","0F78F","0DB94"} },
		{ n="Oath-breaker Coward", l=23, z="ND", i={"0DC56","0DB96","0F791","0DB94"} },
		{ n="Oathbreaker Archer", l=75, z="GR", i={"27710","27725"} },
		{ n="Oathbreaker Champion", l=75, z="GR", i={"27710","27725"} },
		{ n="Ongburz xx", l=34, d=4, z="ND", i={"0F792","0DCCB"} },
		{ n="Ongburz Berserker", l=32, z="ND", i={"0F792","0DCCB"} },
		{ n="Ongburz Combatant", l=33, d=4, z="ND", i={"0F792","0DCCB"} },
		{ n="Ongburz Man-slayer", l=35, d=4, z="ND", i={"0F792","0F793","0DCCB","0DCCC"} },
		{ n="Ongburz Rock-heaver", l=33, d=4, z="ND", i={"0F792","0DCCB"} },
		{ n="Ongburz Slicer", l=32, z="ND", i={"0F792","0DCCB"} },
		{ n="Ongburz Spear-tosser", l=31, z="ND", i={"0F792","0DCCB"} },
		{ n="Ongburz Tracker", l=26, z="ND", i={"0F791"} },
		{ n="Ongburz Warg-keeper", l=32, z="ND", i={"0F792","0DCCB"} },
		{ n="Orc Grunt", l=74, z="D", i={"27724","27710"} },
		{ n="Orc Guard", l=74, z="D", i={"27724","27710"} },
		{ n="Orc Slaver", l=74, z="D", i={"27724","27710"} },
		{ n="Outcast Forest-hunter", l=17, z="BL", i={"0DB17","0DCBC"} },
		{ n="Ox-clan Archer", l=71, z="D", i={"2770F","27721"} },
		{ n="Pecking Dark-wing", l=49, d=1, z="Er", i={"0DB68"} },
		{ n="Peikko", l=46, z="F", i={"0DB1E","0DCC3","0DB85"} },
		{ n="Peikko Hurler", l=47, z="F", i={"0DCC3"} },
		{ n="Piercing Dark-claw", l=52, d=1, z="M", i={"0DEEA","0DFBC"} },
		{ n="Putrid Bog-slug", l=7, d=-2, z="S", i={"0DAF1","0DBB1"} },
		{ n="Putrid Darkwater", l=20, z="BL", i={"0F78F","0DCC8"} },
		{ n="Rabid Scrub-stalker", l=50, z="Er", i={"0DCC4","0DB1F","0DB86"} },
		{ n="Ravaged Celebrant Wolf", l=75, z="GR", i={"2772A","2770C"} },
		{ n="Ravaging Shadow-warg", l=50, z="Er", i={"0DCC4","0DB1F"} },
		{ n="Ravaging Warg", l=91, z="WR", i={"3A753","3A74D","3A752","3A790"} },
		{ n="Redhorn Goat", l=50, d=-2, z="Er", i={"0DB1F","0DCC4","0DB86"} },
		{ n="Rending Fissure-worm", l=48, z="MM", i={"0DCC4"} },
		{ n="Restless Thicktusk", l=8, z="EL", i={"0DCC6","0DB88"} },
		{ n="Restless Longtooth", l=16, z="BL", i={"0DCBC"} },
		{ n="Rift-crawler Creeper", l=50, z="A", i={"0DAEF","0DBAF"} },
		{ n="Rift-crawler Lurker", l=50, z="A", i={"0DC45","0DAEF","0DBAF"} },
--		{ n="Rift-crawler Queen", l=51, D=3, z="A", i={"XX"} },
		{ n="Roaming Thicktusk", l=9, z="EL", i={"0DCC6"} },
		{ n="Roaming Warg", l=31, z="ND", i={"0DB1B","0DCC0"} },
		{ n="Rock-worm", l=75, z="GR", i={"2772A","27735"} },
		{ n="Rotting Barrow-wight", l=20, z="BL", i={"0DAF3","0DCC8","0F78F","0DB94"} },
		{ n="Roving Warg", l=25, z="ND", i={"0DCBF","0DB1A","0DB81"} },
		{ n="Salamander", l=31, z="E", i={"0DCC0","0DAE1"} },
		{ n="Savage Kalpa-kita", l=45, z="F", i={"0DB1E","0DCC3","0DB85"} },
		{ n="Savage Peikko", l=46, z="F", i={"0DB1E","0DCC3"} },
		{ n="Savage Snow-beast", l=40, z="MM", i={"0DCC2","0DB1D"} },
		{ n="Scara Corpse-ravager", l=43, z="A", i={"0DB1D","0DCC2"} },
		{ n="Scara Hunter", l=42, z="A", i={"0DB1D","0DCC2","0DB84"} },
		{ n="Scara Pack-hunter", l=50, z="A", i={"0DB1F","0DB86"} },
--		{ n="Scara Pack-lord", l=51, z="A", i={"XX"} },
		{ n="Scara Pack-master", l=47, z="A", i={"0DB1F","0DCC4","0DB1E","0DCC3"} },
		{ n="Scara Rakeclaw", l=46, z="A", i={"0DB1E","0DCC3"} },
		{ n="Scara Skulker", l=42, z="A", i={"0DB1D","0DCC2"} },
		{ n="Scarred Splintertusk", l=15, z="BL", i={"0DCBC"} },
		{ n="Scavenging Cave-claw", l=47, z="EL", i={"0DAE4","0DCC3"} },
--		{ n="Scrub-lizard", l=51, d=1, z="Er", i={"xx"} },
		{ n="Scrub-land Tusker", l=50, z="Er", i={"0DCC4","0F796"} },
		{ n="Scrub-stalker", l=49, z="Er", i={"0DCC4","0DB1F","0DB86"} },
		{ n="Scurrying Harbour-rat", l=9, z="EL", i={"0DAE7"} },
		{ n="Searing Flame-worm", l=43, z="A", i={"0DB27","0DCC2","0DCC3"} },
		{ n="Shadow-warg", l=50, z="Er", i={"0DCC4","0DB1F","0DB86"} },
		{ n="Shaggy Frost-antler", l=45, d=-2, z="F", i={"0DB1E","0DCC3"} },
		{ n="Shak-hai Warrior", l=75, z="NC", i={"27724","27710"} },
		{ n="Shambling Wight", l=30, z="LL", i={"0DAF5","0DCCB","0F792"} },
		{ n="Shivering Grim", l=46, z="F", i={"0DAEE","0DC5A"} },
		{ n="Shrieking Gloom-wing", l=17, d=1, z="BL", i={"0DCBC"} },
		{ n="Sickle-fly", l=13, z="BL", i={"0DC3D","0DAE8"} },
		{ n="Silent Moor-stalker", l=35, z="T", i={"0DB1C","0DCC1","0DB83"} },
		{ n="Silent Yellowfang", l=22, z="LL", i={"0DB18","0DB80"} },
		{ n="Silt-crawler", l=32, d=-1, z="E", i={"0DCC0","0DBAB","0DAEB"} },
		{ n="Silvan Red-fang", l=44, z="F", i={"0DB1E"} },
		{ n="Silvan Silent-paw", l=44, z="F", i={"0DB1E"} },
		{ n="Skittering Snow-spinner", l=12, z="EL", i={"0DC3D","0DAF1","0DAE8","0DC47","0DBB1"} },
		{ n="Slimy Barrow-crawler", l=18, d=-1, z="BL", i={"0DAE9","0DC3E"} },
		{ n="Slimy Muck-crawler", l=29, d=-1, z="LL", i={"0DAEA","0DBAA","0DC43"} },
		{ n="Small Harvest-fly", l=10, z="S", i={"0DC47","0DAF1"} },
		{ n="Snapper Turtle", l=19, z="BL", i={"0F78F"} },
		{ n="Stinging Gnats", l=7, z="S", i={"0DAF1"} },
		{ n="Snarling Forest-stalker", l=44, d=-2, z="T", i={"0DB1E","0DCC3","0DB85"} },
		{ n="Snow-bOst-Hurler", l=43, z="MM", i={"0DCC2","0DB1D"} },
		{ n="Snow-bOst-Rock-thrower", l=40, z="MM", i={"0DCC2","0DB1D","0DB84"} },
		{ n="Snow-mantle Matron", l=38, z="MM", i={"0DB1D"} },
		{ n="Snow-lurker", l=40, z="MM", i={"0DC43","0DD56"} },
		{ n="Snow-spinner Ambusher", l=12, z="EL", i={"0DC3D","0DAE8","0DAF1","0DC47","0DBB1"} },
		{ n="Snowy Lynx", l=40, z="MM", i={"0DCC2","0DB1D"} },
		{ n="Southern Lookout", l=15, z="BL", i={"0DCC7","0F78E"} },
		{ n="Southern Outlaw", l=15, z="BL", i={"0DCC7","0F78E"} },
		{ n="Southern Raider", l=14, z="BL", i={"0DCC7","0F78E"} },
		{ n="Southern Skirmisher", l=14, z="BL", i={"0DCC7","0F78E"} },
		{ n="Spying Craban", l=50, z="Er", i={"0DB68"} },
		{ n="Starving Field-stalker", l=75, z="GR", i={"2772A","2770C","27733"} },
		{ n="Steppe-elk Hart", l=47, z="F", i={"0DB1E","0DCC3"} },
		{ n="Steppe-elk Hind", l=46, d=-2, z="F", i={"0DB1E","0DCC3"} },
		{ n="Stinging Gnats", l=8, d=-1, z="S", i={"0DAF1"} },
		{ n="Stinging Sickle-fly", l=26, z="ND", i={"0DAEA","0DC40","0DBAA"} },
		{ n="Stone-crawler Devourer", l=38, z="T", i={"0DAED"} },-- "0DC42",
		{ n="Stonedeans Hill-bear", l=91, z="WR", i={"3A753","3A74D"} },
		{ n="Stonedeans Stalker", l=91, z="WR", i={"3A753","3A79C","3A74D"} },
		{ n="Stonehold Warg-keeper", l=46, z="A", i={"0DCCE","0F795"} },
		{ n="Strong Glen-buck", l=37, z="T", i={"0DB1C","0DCC1"} },
		{ n="Strong-grip Barghest", l=19, z="BL", i={"0DCBD","0DB80","0DB18"} },
		{ n="Swamp-lurker", l=43, z="A", i={"0DC43","0DC44"} },
		{ n="Swift Crag-hawk", l=35, d=1, z="T", i={"0DB65","0DC23"} },
		{ n="Tarkrip Basher", l=43, z="A", i={"0F794","0F795"} },
		{ n="Tarkrip Blade", l=19, z="BL", i={"0F78F","0DCC8"} },
		{ n="Tarkrip Fire-thrower", l=44, z="A", i={"0F795","0DCCE"} },
		{ n="Tarkrip Picket", l=22, z="ND", i={"0F78F"} },
		{ n="Tarkrip Raider", l=22, z="ND", i={"0F78F","0DCC8"} },
		{ n="Tarkrip Spear-hurler", l=43, z="A", i={"0F794","0F795","0DCCE","0DCCD"} },
		{ n="Tempest Warg", l=46, z="MM", i={"0DB1E","0DCC3"} },
		{ n="Terrible Dread-mist", l=48, d=3, z="A", i={"0F796"} },
		{ n="Thorn-talon Scout", l=22, d=1, z="LL", i={"0DB61"} },
		{ n="Thorn-talon Sentry", l=22, d=1, z="LL", i={"0DB61"} },
		{ n="Thickjaw Cub", l=7, z="EL", i={"0DCC6"} },
		{ n="Thicktusk Sow", l=9, z="EL", i={"0DCC6","0DB88"} },
		{ n="Thieving Shrew", l=7, z="S", i={"0DB21","0DCC6"} },
		{ n="Haldirith Buck", l=75, z="GR", i={"2772A","2770C"} },
		{ n="Haldirith Doe", l=75, d=-2, z="GR", i={"2772A","2770C"} },
		{ n="Haldirith Matron", l=75, z="GR", i={"2772A","2770C"} },
		{ n="Tomb-robber Ambusher", l=35, z="E", i={"0DCCB","0F792"} },
		{ n="Tundra Bear", l=46, z="F", i={"0DCC3","0DB1E"} },
		{ n="Twisted Arm", l=32, d=1, z="LL", i={"0DAF5"} },
		{ n="Twisted Holly", l=48, d=3, z="Er", i={"0DC30","0DD58"} },
		{ n="Twisted Wight", l=32, d=4, z="LL", i={"0DAF5","0F792","0DCCB"} },
		{ n="Ungund Skirmisher", l=75, z="GR", i={"27710","27724"} },
		{ n="Uruk-hai Captain", l=92, z="WR", i={"3A72A"} },
		{ n="Uruk-hai Marauder", l=78, z="ER", i={"27710"} },
		{ n="Uruk-hai Sentry", l=92, z="WR", i={"3A72A"} },
		{ n="Vale Prowler", l=8, z="EL", i={"0DCC6","0DB88"} },
		{ n="Warg Pack-master", l=94, z="WR", i={"3A752","3A757"} },
		{ n="Warg-rider Sentry", l=92, z="WR", i={"3A72A","3A799"} },
		{ n="Wary Tomb-robber", l=36, z="E", i={"0DCCC","0F793"} },
		{ n="Venom-bite Creeper", l=75, z="GR", i={"2771A","2772D"} },
		{ n="Vicious Plains-hound", l=75, z="GR", i={"2772A","2770C"} },
		{ n="Vicious Shattertusk", l=22, z="LL", i={"0DCBD"} },
		{ n="Vicious War-hound", l=74, z="D", i={"2772A","2770C","27733"} },
		{ n="Vile Barghest", l=18, z="BL", i={"0DCBD","0DB80","0DB18"} },
		{ n="Vile Bog-prowler", l=28, z="LL", i={"0DC40"} },
		{ n="Vile Corpse-rat", l=37, z="T", i={"0DAE2","0DCC1"} },
		{ n="Vile Kergrim", l=37, z="E", i={"0DCC1","0DB83"} },
		{ n="Wailing Ironbound", l=48, z="A", i={"0F796","0DCCF","0DCCE"} },
		{ n="Wandering Cruel-beak", l=21, d=1, z="ND", i={"0DC1F","0DB61"} },
		{ n="Wandering Dark-wing", l=50, d=1, z="Er", i={"0F797","0DEEA"} },
		{ n="Wandering Glen-hind", l=37, z="T", i={"0DB1C","0DCC1"} },
		{ n="Warg Bone-chewer", l=23, z="LL", i={"0DCBD","0DB18","0DB80"} },
		{ n="Wary Tomb-robber", l=33, z="E", i={"0F792"} },
		{ n="Whiskerback Digger", l=35, z="T", i={"0DAE1","0DAE2","0DCC1"} },
		{ n="Whiskerback Scavenger", l=33, z="T", i={"0DAE1","0DCC0"} },
		{ n="White Hand Archer", l=50, z="A", i={"0F796","0DCCF","0F797"} },
		{ n="White Hand Bladesnapper", l=50, z="A", i={"0F796","0F797"} },
		{ n="White Hand Guard", l=23, z="LL", i={"0DCC8","0F78F"} },
		{ n="White Hand Lobber", l=23, z="LL", i={"0DCC8","0F78F"} },
		{ n="White Hand Pillager", l=22, z="LL", i={"0DCC8","0F78F"} },
		{ n="White Hand Skirmisher", l=72, z="D", i={"2770F","27721" ,"2770F"} },
		{ n="White Hand Spear-thrower", l=23, z="LL", i={"0DCC8","0F78F"} },
		{ n="White Hand Stormcaller", l=50, z="A", i={"0F797","0DCCF"} },
		{ n="White Hand Warrior", l=72, z="D", i={"2770F","27721" ,"2770F"} },
--		{ n="White-hand Howler", l=51, z="Er", i={"xx"} },
		{ n="White-hand Ravager", l=50, z="Er", i={"0DB1F"} },
		{ n="Whitemane Scavenger", l=35, z="E", i={"0DB1C","0DCC1"} },
		{ n="Whitemane Wolf", l=47, z="MM", i={"0DB1E","0DCC3","0DB85"} },
		{ n="Whitemane-leader", l=47, z="MM", i={"0DB1F","0DCC4"} },
		{ n="Wight Dread-warrior", l=38, z="T", i={"0DCCC","0F794"} },
		{ n="Wild Bloodfang", l=48, z="A", i={"0DB68","0DCC4"} },
		{ n="Wild Gramsfoot", l=12, z="S", i={"0F79E","0DCD1","0F78E","0DCC7"} },
		{ n="Wild Grey Wolf", l=8, z="EL", i={"0DCC6","0DB21"} },
		{ n="Wild Hill-toad", l=9, d=-2, z="S", i={"0DCC6","0DAE7"} },
		{ n="Wild Hill Goat", l=74, d=-2, z="GR", i={"2772A","2770C"} },
		{ n="Wild Razortooth", l=20, z="ND", i={"0DCBD","0DB80"} },
		{ n="Wild Tusker", l=7, z="S", i={"0DCC6"} },
		{ n="Winter-worm", l=46, z="F", i={"0DB28","0DCC3","0DC01"} },
		{ n="Withering Fire-drake", l=42, d=4, z="A", i={"0DB27","0DCC2"} },
		{ n="Wolf", l=10, z="S", i={"0DB21"} },
		{ n="Wolf Hunter", l=11, z="S", i={"0DCC6","0DB21"} },
		{ n="Wretched Rock-worm", l=41, z="MM", i={"0DB27"} },
--		{ n="Writhing Stone-crawler", l=35, d=1, z="T", i={"00"} },
		{ n="Young Field-bear", l=14, z="BL", i={"0DCBC","0DB17"} },
		{ n="Young Glen-buck", l=33, z="T", i={"0DB1B"} },
		{ n="Young Vale-bear", l=8, z="EL", i={"0DB21"} },
		{ n="Young Glen-buck", l=50, z="T", i={"0DB1B"} },
	}
}
Region = { Eriador=1, Rhovanion=2, Gondor=3 }

DT_Data.zone = { }
for n,t in pairs(DT_Data.loc) do
	local z = t.zone
	if not DT_Data.zone[z] then DT_Data.zone[z] = {} end
	DT_Data.zone[z][n] = true
end

zones = { EL="Ered Luin", S="Auenland", BL="Breeland", LL="Einsame Lande",
		ND="Nordhöhen", E="Evendim", T="Trollhöhen", MM="Nebelgebirge",
		F="Forochel", A="Angmar", Er="Eregion", M="Moria", D="Dunland",
		NC="Nan Curunir", GR="Großer Fluss", ER="Ost-Rohan", WR="West-Rohan",
		WG="West-Gondor", CG="Zentrum Gondors", }
Zone = { }
for code,name in pairs(zones) do Zone[name] = code end

Diff = { [1]="Swarm", [2]="Normal", [3]="Signature", [4]="Elite",
		[5]="Elite Master", [6]="Nemesis" } -- , [7]="Arch-nemesis"
DiffCode = { "sw","n","s","e","em","n" } -- ,"an"

for ix,t in pairs(DT_Data.mob) do
	for i,id in pairs(t.i) do
		local it = DT_Data.id[id]
		if not it then print("Bad data for "..t.n..", "..id) break end
		if not it.m then it.m = {} end
		it.m[ix] = true
	end
end
